Pages/Logowanie/LogIn.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using webapp.Data;
using webapp.Models;

namespace webapp.Pages
{

    public class LogInModel : PageModel
    {
        [BindProperty]
        public Klienci klient { get; set; }
        public string Msg;
        public bool isPracownik = false;
        private KinoContext db;
        public LogInModel(KinoContext _db)
        {
            db = _db;
        }

        public void OnGet()
        {
            klient = new Klienci();



        }

        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToPage("Index");
        }

        public IActionResult OnPost()
        {
            var acc = login(klient.nr_telefonu, klient.haslo);
            if (acc == null)
            {
                var prac = loginprac(klient.nr_telefonu, klient.haslo);
                if (prac == null)
                {
                    Msg = "Invalid";
                    return Page();
                }
                else
                {
                    HttpContext.Session.SetString("username", prac.nr_telefonu.ToString());
                    if(prac.isAdmin==true)
                    return RedirectToPage("../Common/MainAdmin");
                    else
                        return RedirectToPage("../Common/MainPrac");
                }
            }
            else
            {
                HttpContext.Session.SetString("username", acc.nr_telefonu.ToString());
                return RedirectToPage("../Common/MainKlient");
            }

        }

        private Klienci login(int username, string password)
        {
            var account = db.Klienci.SingleOrDefault(a => a.nr_telefonu.Equals(username));
            if (account != null)
            {
                if (BCrypt.Net.BCrypt.Verify(password, account.haslo))
                {
                    return account;
                }
            }
            return null;

        }



        private Pracownicy loginprac(int username, string password)
        {
            var account = db.Pracownicy.SingleOrDefault(a => a.nr_telefonu.Equals(username));
            if (account != null)
            {
                if (BCrypt.Net.BCrypt.Verify(password, account.haslo))
                {
                    return account;
                }
            }
            return null;

        }

    }
}

Pages/Logowanie/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace webapp.Pages.Common
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("../Index");
        }
    }
}

Pages/Logowanie/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using webapp.Data;
using webapp.Models;

namespace webapp.Pages.Logowanie
{
    public class ProfileModel : PageModel
    {

        [BindProperty]
        public Klienci klient { get; set; }
        public static int id;

        private KinoContext db;
        public ProfileModel(KinoContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            var username = HttpContext.Session.GetString("username");
            klient = db.Klienci.SingleOrDefault(a => a.nr_telefonu.ToString().Equals(username));
            id = klient.Id;
        }

        public IActionResult OnPost()
        {
            if (string.IsNullOrEmpty(klient.haslo))
            {

                klient.haslo = db.Klienci.AsNoTracking().SingleOrDefault(a => a.nr_telefonu == klient.nr_telefonu).haslo;
            }
            else
            {
               klient.haslo = BCrypt.Net.BCrypt.HashPassword(klient.haslo);
            }
            klient.Id = id;
            db.SaveChanges();
            db.Entry(klient).State = EntityState.Modified;

                db.SaveChanges();
      

        HttpContext.Session.SetString("username", klient.nr_telefonu.ToString());
            return RedirectToPage("Welcome");
        }
     
    }

}

Pages/Logowanie/SignUp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using BCrypt.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using webapp.Data;
using webapp.Models;

namespace webapp.Pages.Logowanie
{
    public class SignUpModel : PageModel
    {

        [BindProperty]
        public Klienci klient { get; set; }

        private KinoContext db;
        public string Msg;

        public SignUpModel(KinoContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            klient = new Klienci();
        }
        public IActionResult OnPost()
        {
            var acc = login(klient.nr_telefonu);
            if (acc == false)
            {
                klient.haslo = BCrypt.Net.BCrypt.HashPassword(klient.haslo);

                db.Klienci.Add(klient);
                db.SaveChanges();
                return RedirectToPage("/Index");
            }
            else
            {
                if (acc ==true)
                    Msg = Msg + "Ten Nr telefonu jest juz zarejestrowany \n";
                return Page();
            }

        }

        private bool login(int username)
        {
            var account = db.Klienci.SingleOrDefault(a => a.nr_telefonu.Equals(username));
            if (account != null)
            {
                return true;
            }
            var prac= db.Pracownicy.SingleOrDefault(a => a.nr_telefonu.Equals(username));
            if (prac != null)
            {
                return true;
            }
            return false;
        }

    

    }
}

Pages/Logowanie/Welcome.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using webapp.Data;
using webapp.Models;

namespace webapp.Pages.Logowanie
{
    public class WelcomeModel : PageModel
    {
        public Klienci klient { get; set; }

        private KinoContext db;
        public WelcomeModel(KinoContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            var username = HttpContext.Session.GetString("username");
            klient = db.Klienci.SingleOrDefault(a => a.nr_telefonu.ToString().Equals(username));

        }
    }
}

Pages/Logowanie/WelcomePrac.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using webapp.Data;
using webapp.Models;

namespace webapp.Pages.Logowanie
{
    public class WelcomePracModel : PageModel
    {
        public Pracownicy prac { get; set; }

        private KinoContext db;
        public WelcomePracModel(KinoContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            var username = HttpContext.Session.GetString("username");
           prac = db.Pracownicy.SingleOrDefault(a => a.nr_telefonu.ToString().Equals(username));

        }
    }
}

Pages/Logowanie/LogIn.cshtml
@page
@model LogInModel
@{
    ViewData["Title"] = "Logowanie";
    Layout = "../Shared/_LayoutNoone.cshtml";
}

<html>
<body>

    <h3>Zaloguj się</h3>
    @Model.Msg
    <form method="post" asp-page="index">
        <table>
            <tr>
                <td>Numer telefonu</td>
                <td>
                    <input asp-for="@Model.klient.nr_telefonu" />
                </td>
            </tr>
            <tr>
                <td>Hasło</td>
                <td>
                    <input asp-for="@Model.klient.haslo" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Zaloguj" />
                    <br />
                    <a asp-page="signup">Zarejestruj się</a>
                </td>
            </tr>
        </table>
    </form>

</body>
</html>

Pages/Logowanie/Logout.cshtml
@page
@model webapp.Pages.Common.LogoutModel
@{
}

Pages/Logowanie/Profile.cshtml
@page
@model webapp.Pages.Logowanie.ProfileModel
@{
    ViewData["Title"] = "Edycja profilu";
    Layout = "../Shared/_LayoutUser.cshtml";
}
<html>

<body>

    <h3>Edycja profilu</h3>
    <form method="post" asp-page="profile">
        <table>
            <tr>
                <td>Numer telefonu</td>
                <td>
                    <input asp-for="@Model.klient.nr_telefonu" />
                </td>
            </tr>
            <tr>
                <td>Hasło</td>
                <td>
                    <input type="password" asp-for="@Model.klient.haslo" />
                </td>
            </tr>
            <tr>
                <td>Imie</td>
                <td>
                    <input asp-for="@Model.klient.imie" />
                </td>
            </tr>
            <tr>
                <td>Nazwisko</td>
                <td>
                    <input asp-for="@Model.klient.nazwisko" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Zapisz " />   |
                    <a asp-page="Welcome">Powrót</a>
                </td>

            </tr>
        </table>
    </form>

</body>
</html>

Pages/Logowanie/SignUp.cshtml
@page
@model webapp.Pages.Logowanie.SignUpModel
@{
    ViewData["Title"] = "Rejestracja";
    Layout = "../Shared/_LayoutNoone.cshtml";
}
<html>
<head>
 
    @Model.Msg
</head>
<body>

    <h3>Zarejestruj się</h3>
    <form method="post" asp-page="signup">
        <table>
            <tr>
                <td>Numer telefonu</td>
                <td>
                    <input asp-for="@Model.klient.nr_telefonu" />
                </td>
            </tr>
            <tr>
                <td>Hasło</td>
                <td>
                    <input asp-for="@Model.klient.haslo" />
                </td>
            </tr>
            <tr>
                <td>Imie</td>
                <td>
                    <input asp-for="@Model.klient.imie" />
                </td>
            </tr>
            <tr>
                <td>Nazwisko</td>
                <td>
                    <input asp-for="@Model.klient.nazwisko" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Zarejestruj" />
                    <br />
                    <a asp-page="/LogIn">Zaloguj się</a>
                </td>
            </tr>
        </table>
    </form>

</body>
</html>

Pages/Logowanie/Welcome.cshtml
@page
@model webapp.Pages.Logowanie.WelcomeModel
@{
    ViewData["Title"] = "Twój profil";
    Layout = "../Shared/_LayoutUser.cshtml";
}
@using Microsoft.AspNetCore.Http
<html>
<head>
    <meta name="viewport" content="width=device-width" />

</head>
<body>
    <h3>Twój profil:</h3>
    <br />
    Numer telefonu: @Model.klient.nr_telefonu
    <br />
    <br />
    Imie: @Model.klient.imie
    <br />
    <br />
    Nazwisko: @Model.klient.nazwisko
    <br />
    <br />
    <a asp-page="/Index" asp-page-handler="logout">Wyloguj się</a>
    <br />
    <br />
    <a asp-page="profile">Edytuj Profil</a>
</body>
</html>

Pages/Logowanie/WelcomePrac.cshtml
@page
@model webapp.Pages.Logowanie.WelcomePracModel
@{
    ViewData["Title"] = "Twój profil";
    Layout = "../Shared/_LayoutPrac.cshtml";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />

</head>

<body>
    <h3>Twój profil:</h3>
    <br />
    Numer telefonu: @Model.prac.nr_telefonu
    <br />
    <br />
    Imie: @Model.prac.imie
    <br />
    <br />
    Nazwisko: @Model.prac.nazwisko
    <br />
    <br />
    Stanowisko: @Model.prac.stanowisko
    <br />
    <br />
    Data Zatrudnienia: @Model.prac.data_zatrudnienia
    <br />
    <br />


    <a asp-page="/Index" asp-page-handler="logout">Wyloguj się</a>
    <br />
</body>
</html>